// <auto-generated />
using System;
using Kuafor.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuafor.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalisanHizmet", b =>
                {
                    b.Property<int>("UzmanliklarId")
                        .HasColumnType("int");

                    b.Property<int>("VerebilenCalisanlarId")
                        .HasColumnType("int");

                    b.HasKey("UzmanliklarId", "VerebilenCalisanlarId");

                    b.HasIndex("VerebilenCalisanlarId");

                    b.ToTable("CalisanHizmet", (string)null);
                });

            modelBuilder.Entity("HizmetSalon", b =>
                {
                    b.Property<int>("SalonlarId")
                        .HasColumnType("int");

                    b.Property<int>("SunulanHizmetlerId")
                        .HasColumnType("int");

                    b.HasKey("SalonlarId", "SunulanHizmetlerId");

                    b.HasIndex("SunulanHizmetlerId");

                    b.ToTable("SalonHizmet", (string)null);
                });

            modelBuilder.Entity("Kuafor.Core.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("Kuafor.Core.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Kullanici");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kuafor.Core.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("ToplamSureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamUcret")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("HizmetId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("Kuafor.Core.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalismaSaatleriAciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("Kuafor.Core.UygunlukZamani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.ToTable("UygunlukZamanlari");
                });

            modelBuilder.Entity("SalonYonetici", b =>
                {
                    b.Property<int>("YoneticilerId")
                        .HasColumnType("int");

                    b.Property<int>("YonetilenSalonlarId")
                        .HasColumnType("int");

                    b.HasKey("YoneticilerId", "YonetilenSalonlarId");

                    b.HasIndex("YonetilenSalonlarId");

                    b.ToTable("SalonYonetici", (string)null);
                });

            modelBuilder.Entity("Kuafor.Core.Calisan", b =>
                {
                    b.HasBaseType("Kuafor.Core.Kullanici");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.HasIndex("SalonId");

                    b.HasDiscriminator().HasValue("Calisan");
                });

            modelBuilder.Entity("Kuafor.Core.Musteri", b =>
                {
                    b.HasBaseType("Kuafor.Core.Kullanici");

                    b.HasDiscriminator().HasValue("Musteri");
                });

            modelBuilder.Entity("Kuafor.Core.Yonetici", b =>
                {
                    b.HasBaseType("Kuafor.Core.Kullanici");

                    b.HasDiscriminator().HasValue("Yonetici");
                });

            modelBuilder.Entity("CalisanHizmet", b =>
                {
                    b.HasOne("Kuafor.Core.Hizmet", null)
                        .WithMany()
                        .HasForeignKey("UzmanliklarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuafor.Core.Calisan", null)
                        .WithMany()
                        .HasForeignKey("VerebilenCalisanlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HizmetSalon", b =>
                {
                    b.HasOne("Kuafor.Core.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuafor.Core.Hizmet", null)
                        .WithMany()
                        .HasForeignKey("SunulanHizmetlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuafor.Core.Randevu", b =>
                {
                    b.HasOne("Kuafor.Core.Calisan", "Calisan")
                        .WithMany("Randevular")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kuafor.Core.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kuafor.Core.Musteri", "Musteri")
                        .WithMany("Randevular")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Kuafor.Core.UygunlukZamani", b =>
                {
                    b.HasOne("Kuafor.Core.Calisan", "Calisan")
                        .WithMany("UygunlukZamanlari")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("SalonYonetici", b =>
                {
                    b.HasOne("Kuafor.Core.Yonetici", null)
                        .WithMany()
                        .HasForeignKey("YoneticilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuafor.Core.Salon", null)
                        .WithMany()
                        .HasForeignKey("YonetilenSalonlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuafor.Core.Calisan", b =>
                {
                    b.HasOne("Kuafor.Core.Salon", "Salon")
                        .WithMany("Calisanlar")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Kuafor.Core.Salon", b =>
                {
                    b.Navigation("Calisanlar");
                });

            modelBuilder.Entity("Kuafor.Core.Calisan", b =>
                {
                    b.Navigation("Randevular");

                    b.Navigation("UygunlukZamanlari");
                });

            modelBuilder.Entity("Kuafor.Core.Musteri", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
